
#
/system/framework/framework.jar
#
/system/framework/framework.jar
0
(/system/framework/framework-graphics.jar33
0
(/system/framework/framework-graphics.jar33

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
1
-/system/framework/mediatek-telephony-base.jar
1
-/system/framework/mediatek-telephony-base.jar
3
//system/framework/mediatek-telephony-common.jar
3
//system/framework/mediatek-telephony-common.jar
9
5/system/framework/mediatek-carrier-config-manager.jar
9
5/system/framework/mediatek-carrier-config-manager.jar
)
%/system/framework/mediatek-common.jar
)
%/system/framework/mediatek-common.jar
,
(/system/framework/mediatek-framework.jar
,
(/system/framework/mediatek-framework.jar
-
)/system/framework/mediatek-ims-common.jar
-
)/system/framework/mediatek-ims-common.jar
+
'/system/framework/mediatek-ims-base.jar
+
'/system/framework/mediatek-ims-base.jar
1
-/system/framework/mediatek-telecom-common.jar
1
-/system/framework/mediatek-telecom-common.jar
,
(/system_ext/framework/miui-framework.jar
,
(/system_ext/framework/miui-framework.jar
3
//system_ext/framework/miui-telephony-common.jar
3
//system_ext/framework/miui-telephony-common.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar